# Generated by Django 5.2.6 on 2025-09-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roll_no', models.IntegerField()),
                ('F_name', models.CharField(max_length=100)),
                ('L_name', models.CharField(max_length=100)),
            ],
        ),
    ]
