# Generated by Django 5.2.6 on 2025-09-08 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='F_name',
            new_name='f_name',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='L_name',
            new_name='l_name',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='Roll_no',
            new_name='roll_no',
        ),
    ]
